name: financetrackerapp
description: "Personal Finance Tracker with Virtual Pocketing & Smart Ledger"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: any

  # Supabase (Auth + Database + Storage)
  supabase_flutter: any

  # Database Lokal (Offline Support)
  sqflite: any
  path: any

  # Charts / Visualisasi
  fl_chart: ^1.2.0

  # Export Data
  csv: ^8.0.0
  pdf: ^3.12.0
  printing: ^5.14.3

  # Environment Variables (API Key Security)
  flutter_dotenv: any

  # Utilities
  intl: any
  uuid: any
  image_picker: any
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  connectivity_plus: any
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
